config/routes.rb
OcCharts::Application.routes.draw do

  resources :stock_charts

  match 'goto_stock_chart', :to => redirect { |params, req|
    query_params = req.parameters[:stock_chart_query]
    query_params = req.parameters if query_params.nil?
    query = StockChartQuery.new(query_params)

    next "/stock_charts/#{req.parameters.to_query}" if query.symbol.blank?  #error case
    "/stock_charts/#{query.symbol}?#{query.serializable_hash.to_query(:stock_chart_query)}"
  }

  resources :stock_prices, :only => [:show]

end

app/models/stock_chart_query.rb
class StockChartQuery
  include ActiveAttr::Model

  attribute :symbol, :type => String
  attribute :start_date, :type => Date
  attribute :end_date, :type => Date

  attr_accessor :symbol, :start_date, :end_date

  validates :symbol,   :presence => true

  validates_date :start_date,
                 if: "end_date",   # mutual inclusive or exclusive with start_date
                 before: lambda{ Date.today }, before_message: "must be a date in the past"

  validates_date :end_date,
                 if: "start_date", # mutual inclusive or exclusive with end_date
                 before: lambda{ Date.today }, before_message: "must be a date in the past",
                 on_or_after: :start_date, on_or_after_message: "must be on or after start date"


  def initialize(attrs = {} )
    attrs.each do |name, value|
      # calling the attr accessor
      self.send("#{name}=", value) if self.respond_to? "#{name}="
    end
  end

  def persisted?
    false
  end

  def attributes
    {
        symbol: symbol,
        start_date: start_date,
        end_date: end_date
    }
  end
end

app/models/stock_price.rb
class StockPrice  < ActiveResource::Base
  self.site = "http://ichart.finance.yahoo.com"
  self.element_name = "table"
  self.collection_name="table"
  self.include_root_in_json = false

  #"?s=WU&a=01&b=19&c=2010&d=01&e=19&f=2010&g=d&ignore=.csv"
  # http://ichart.finance.yahoo.com/table.csv?s=AAPL&a=10&b=19&c=2000&d=11&e=19&f=2000&g=d&ignore=.csv
  # a - month (0=Jan)
  self.format= ActiveResource::Formats::CsvFormat

  schema do
    string 'date'

    # note: yahoo return string
    float 'low', 'open', 'close', 'high'
  end

  def low()   attributes[:low].to_f end
  def open()  attributes[:open].to_f end
  def close() attributes[:close].to_f end
  def high()  attributes[:high].to_f end

  class << self
    def query_string(options)
      "?#{hash_to_query(options)}" unless options.nil? || options.empty?
    end

    def hash_to_query(options)
      options.collect do |key, value|
        value.to_query(key)
      end * '&'
    end
  end


  def self.find_historical_prices(symbol, date_range, interval = :daily)
    start_at = date_range.begin
    end_at = date_range.end


    self.find(:all, :params => {
        s: symbol,
        a: (start_at.month - 1),
        b: start_at.day,
        c: start_at.year,
        d: (end_at.month - 1),
        e: end_at.day,
        f: end_at.year,
        g: 'd',
        ignore: '.csv'
    })
  end


  def as_json(options = {})
    [
=begin
        Col 0: String (discrete) used as a group label on the X axis, or number, date, datetime or timeofday (continuous) used as a value on the X axis.
        Col 1: Number specifying the low/minimum value of this marker. This is the base of the candle's center line. The column label is used as the series label in the legend (while the labels of the other columns are ignored).
        Col 2: Number specifying the opening/initial value of this marker. This is one vertical border of the candle. If less than the column 3 value, the candle will be filled; otherwise it will be hollow.
        Col 3: Number specifying the closing/final value of this marker. This is the second vertical border of the candle. If less than the column 2 value, the candle will be hollow; otherwise it will be filled.
        Col 4: Number specifying the high/maximum value of this marker. This is the top of the candle's center line.
                                                                                                                                                                                                                                                                                                                                                                Col 5 [Optional]: A tooltip for the candlestick.
=end
        self.date,
        self.low,
        self.open,
        self.close,
        self.high
    ]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stock_charts_controller.rb
class StockChartsController < ApplicationController

  # GET /stock_charts
  # GET /stock_charts.json
  def index
    @stock_chart_query = StockChartQuery.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stock_charts }
    end
  end

  # GET /stock_charts/1
  # GET /stock_charts/1.json
  def show
    @stock_chart_query = StockChartQuery.new(params[:stock_chart_query])

    unless @stock_chart_query.valid?
      logger.warn("missing symbol: #{@stock_chart_query.errors.as_json}")
      flash[:error] = 'missing stock symbol'
      redirect_to :action => 'index'
      return 
    end

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /stock_charts/new
  # GET /stock_charts/new.json
=begin
  def new
    @stock_chart = StockChart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stock_chart }
    end
  end
=end

  # GET /stock_charts/1/edit
=begin
  def edit
    @stock_chart = StockChart.find(params[:id])
  end
=end

  # POST /sto0ck_charts
  # POST /stock_charts.json
=begin
  def create
    @stock_chart = StockChart.new(params[:stock_chart])

    respond_to do |format|
      if @stock_chart.save
        format.html { redirect_to @stock_chart, notice: 'Stock chart was successfully created.' }
        format.json { render json: @stock_chart, status: :created, location: @stock_chart }
      else
        format.html { render action: "new" }
        format.json { render json: @stock_chart.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # PUT /stock_charts/1
  # PUT /stock_charts/1.json
=begin
  def update
    @stock_chart = StockChart.find(params[:id])

    respond_to do |format|
      if @stock_chart.update_attributes(params[:stock_chart])
        format.html { redirect_to @stock_chart, notice: 'Stock chart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stock_chart.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /stock_charts/1
  # DELETE /stock_charts/1.json
=begin
  def destroy
    @stock_chart = StockChart.find(params[:id])
    @stock_chart.destroy

    respond_to do |format|
      format.html { redirect_to stock_charts_url }
      format.json { head :no_content }
    end
  end
=end
end

app/controllers/stock_prices_controller.rb
class StockPricesController < ApplicationController

  # GET /stock_price/1.json
  def show
    logger.info("param=#{params}")

    symbol = params[:id]
    start_date = params[:start_date]
    end_date = params[:end_date]
    date_range = (Date.today - 30)..(Date.today - 1)
    logger.info("date_range1=#{date_range}")

    @stock_prices = StockPrice.find_historical_price(symbol, date_range)

    logger.info("prices=#{@stock_prices}")

    respond_to do |format|
      format.json { render json: @stock_prices }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def include_controller_javascript
    javascript_include_tag params[:controller] if Rails.application.assets.find_asset("#{params[:controller]}")
    # javascript_include_tag "#{params[:controller]}_#{params[:action]}" if OcCharts::Application.assets.find_asset("#{params[:controller]}_#{params[:action]}")
  end

  def include_controller_stylesheet
    stylesheet_link_tag params[:controller] if Rails.application.assets.find_asset("#{params[:controller]}")
    # stylesheet_link_tag {params[:controller]}_#{params[:action]}" if OcCharts::Application.assets.find_asset("#{params[:controller]}_#{params[:action]}")
  end

end

app/helpers/stock_charts_helper.rb
module StockChartsHelper
end

app/helpers/stock_prices_helper.rb
module StockPricesHelper
end

app/views/layouts/_header.html.erb
<div class="base-header">
  <div class="company-logo">OC Ideas Logo</div>
  <div class="company-sub-logo">Ideas without bound</div>
  <div class="line-separator" />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OcCharts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= include_controller_javascript %>
  <%= yield :javascript_includes %>
<!--
  <%= include_controller_stylesheet %>
-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => 'layouts/header' %>

<%= yield %>

<!-- %= render :partial => 'footer' % -->

</body>
</html>

app/views/stock_charts/_form.html.erb
<%= form_for(@stock_chart) do |f| %>
  <% if @stock_chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock_chart.errors.count, "error") %> prohibited this stock_chart from being saved:</h2>

      <ul>
      <% @stock_chart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stock_charts/edit.html.erb
<h1>Editing stock_chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock_chart %> |
<%= link_to 'Back', stock_charts_path %>

app/views/stock_charts/index.html.erb
<h1>Stock Chart</h1>

<% content_for :javascript_includes do %>
  <script type="text/javascript">
      $(function() {
          $('.datepicker').datepicker(
                  {
                      dateFormat: "yy-mm-dd"
                  }
          );
      });
  </script>
<% end %>

<%= form_for @stock_chart_query, :url => goto_stock_chart_url, :method => 'get'  do |f| %>
    <% if @stock_chart_query.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@stock_chart_query.errors.count, "error") %>: </h2>
          <ul>
            <% @stock_chart_query.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.label :symbol, "Stock Symbol" %><%= f.text_field :symbol %> <br/>
    <%= f.label :start_date, "Start Date" %> <%= f.text_field :start_date, :class => 'datepicker' %>
    <%= f.label :end_date, "End Date" %> <%= f.text_field :end_date, :class => 'datepicker' %> <br/>
    <%= f.submit "Draw Chart" %>
<% end %>


<!--
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

< % @stock_charts.each do |stock_chart| %>
  <tr>
    <td>< %= link_to 'Show', stock_chart %></td>
    <td>< %= link_to 'Edit', edit_stock_chart_path(stock_chart) %></td>
    <td>< %= link_to 'Destroy', stock_chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
< % end %>
</table>
-->

app/views/stock_charts/new.html.erb
<h1>New stock_chart</h1>

<%= render 'form' %>

<%= link_to 'Back', stock_charts_path %>

app/views/stock_charts/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for :javascript_includes do %>
  <script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script type="text/javascript">
      google.load('visualization', '1', {packages: ['corechart']});
      google.setOnLoadCallback(function() {
          var visual_div = $('#visualization');
          drawVisualization(visual_div);
      });
  </script>
<% end %>

<%= tag("div", :id => 'visualization', :data => {
        url: stock_price_url(@stock_chart_query.serializable_hash),
        width: 1200,
        height: 600
}) %>


<!-- %= link_to 'Edit', edit_stock_chart_path(@stock_chart) % -->
<!-- %= link_to 'Back', stock_charts_path % -->